# syntax = docker/dockerfile:1.7

FROM --platform=linux/amd64 docker-cja-arrow-dev.dr-uw2.adobeitc.com/node-22-bookworm-slim

COPY ballista/scheduler/ui/ /ballista-scheduler-ui

RUN <<eof
  #!/bin/bash
  cd /ballista-scheduler-ui
  rm -rf build
  rm -rf node_modules
  yarn
eof

WORKDIR "/ballista-scheduler-ui"

